#:schema node_modules/wrangler/config-schema.json
name = "nike-cloudeflare"
main = "./server.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[env.production]
# Specify your build output directory
pages_build_output_dir = "dist"  # Adjust this according to your build setup

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-12-09"

kv_namespaces = [{ binding = "cache", id = "c6716a39b38746d7a87b221a719eeda3" }]

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

[build]
command = "npm run build"

[vars]
REACT_APP_BASE_URL="https://composer.dealerdashboard.universalcommerce.io"
