name = "nike-cloudeflare"
main = "./server.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

compatibility_date = "2024-11-06"
# Move KV namespace here
kv_namespaces = [
  { binding = "cache", id = "c6716a39b38746d7a87b221a719eeda3" }
 
]

[assets]
directory = "./build/client"

[build]
command = "npm run build"

[vars]
REACT_APP_BASE_URL = "http://4.240.112.193:50102"
pages_build_output_dir = "./public"

[env.production]
compatibility_date = "2024-11-06"

