name = "nike-cloudflare"
main = "./server.ts"
compatibility_date = "2024-12-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[vars]
REACT_APP_BASE_URL = "http://4.240.112.193:50102"

[[kv_namespaces]]
binding = "cache"
id = "c6716a39b38746d7a87b221a719eeda3"

[assets]
directory = "./build/client"

[env.production]
compatibility_date = "2024-12-23"
