#:schema node_modules/wrangler/config-schema.json
name = "nike-cloudeflare"
main = "./server.ts"
workers_dev = true

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-12-05"

kv_namespaces = [{ binding = "cache", id = "c6716a39b38746d7a87b221a719eeda3" }]

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

[build]
command = "npm run build"

[vars]
GITHUB_OWNER = "vishalgCnetric"
GITHUB_REPO = "nike-cloudflare"
